# .github/workflows/app.yaml
name: PyTest
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install package
        run: |
          pip install . 
      - name: Test with pytest
        run: |
          python -m pytest -vv tests/*py